services:
    _defaults:
        public: true

    Aaxis\Bundle\OntologyBundle\Controller\OntologySystemController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Aaxis\Bundle\OntologyBundle\Controller\OntologyEntityController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_entity.entity_provider, key: Oro\Bundle\EntityBundle\Provider\EntityProvider }
            - { name: container.service_subscriber, id: oro_entity.entity_field_provider, key: Oro\Bundle\EntityBundle\Provider\EntityFieldProvider }

    Aaxis\Bundle\OntologyBundle\Controller\OntologyConnectorController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Aaxis\Bundle\OntologyBundle\Controller\OntologyDataController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: Aaxis\Bundle\OntologyBundle\Manager\OntologyDataApiManager, key: Aaxis\Bundle\OntologyBundle\Manager\OntologyDataApiManager }

    Aaxis\Bundle\OntologyBundle\Controller\OntologyConfigController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_config.global, key: Oro\Bundle\ConfigBundle\Config\ConfigManager }
            - { name: container.service_subscriber, id: oro_security.encoder.default, key: Oro\Bundle\SecurityBundle\Encoder\SymmetricCrypterInterface }

    Aaxis\Bundle\OntologyBundle\Controller\OntologyEventController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Aaxis\Bundle\OntologyBundle\Controller\OntologyFlowController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_config.global, key: Oro\Bundle\ConfigBundle\Config\ConfigManager }
            - { name: container.service_subscriber, id: Aaxis\Bundle\OntologyBundle\Manager\PhpMethodInvoker, key: Aaxis\Bundle\OntologyBundle\Manager\PhpMethodInvoker }
            - { name: container.service_subscriber, id: Aaxis\Bundle\OntologyBundle\Manager\FlowHistoryArchiver, key: Aaxis\Bundle\OntologyBundle\Manager\FlowHistoryArchiver }
            - { name: container.service_subscriber, id: Aaxis\Bundle\OntologyBundle\Manager\OntologyFlowEventEmitter, key: Aaxis\Bundle\OntologyBundle\Manager\OntologyFlowEventEmitter }

    Aaxis\Bundle\OntologyBundle\Api\OntologyFlowApiController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_config.global, key: Oro\Bundle\ConfigBundle\Config\ConfigManager }

    Aaxis\Bundle\OntologyBundle\Api\OntologyDataApiController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: Aaxis\Bundle\OntologyBundle\Manager\OntologyDataApiManager, key: Aaxis\Bundle\OntologyBundle\Manager\OntologyDataApiManager }
            - { name: container.service_subscriber, id: oro_config.global, key: Oro\Bundle\ConfigBundle\Config\ConfigManager }
