dynamic-imports:
    aaxisontology:
        - aaxisontology/js/app/components/system-component
        - aaxisontology/js/app/components/entity-component
        - aaxisontology/js/app/components/data-view-component
        - aaxisontology/js/app/components/event-component
        - aaxisontology/js/app/components/flow-component
        - aaxisontology/js/app/components/flow-editor-component
        - aaxisontology/js/app/components/connector-config-component
        - aaxisontology/js/app/components/connector-view-test-component
        - aaxisontology/js/app/components/bucket-config-test-component
